// This file is auto-generated by @hey-api/openapi-ts

export const EventRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            maxLength: 255
        },
        description: {
            type: [
                'string',
                'null'
            ]
        },
        event_type: {
            type: 'string',
            enum: [
                'school',
                'reminder'
            ]
        },
        due_date: {
            type: 'string',
            format: 'date-time'
        },
        tag_id: {
            type: [
                'integer',
                'null'
            ]
        }
    },
    required: [
        'title',
        'description',
        'event_type',
        'due_date'
    ],
    title: 'EventRequest'
} as const;

export const EventResourceSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        title: {
            type: 'string'
        },
        description: {
            type: [
                'string',
                'null'
            ]
        },
        event_type: {
            type: 'string'
        },
        due_date: {
            type: 'string',
            format: 'date-time'
        },
        created_at: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        },
        tag: {
            $ref: '#/components/schemas/TagResource'
        }
    },
    required: [
        'id',
        'title',
        'description',
        'event_type',
        'due_date',
        'created_at',
        'updated_at'
    ],
    title: 'EventResource'
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string'
        }
    },
    required: [
        'email',
        'password'
    ],
    title: 'LoginRequest'
} as const;

export const ProjectRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            maxLength: 255
        },
        description: {
            type: [
                'string',
                'null'
            ],
            maxLength: 255
        },
        is_completed: {
            type: 'boolean'
        },
        tag_id: {
            type: [
                'integer',
                'null'
            ]
        },
        parent_id: {
            type: [
                'integer',
                'null'
            ]
        }
    },
    required: [
        'title'
    ],
    title: 'ProjectRequest'
} as const;

export const ProjectResourceSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        title: {
            type: 'string'
        },
        description: {
            type: [
                'string',
                'null'
            ]
        },
        is_completed: {
            type: 'boolean'
        },
        completed_at: {
            type: [
                'integer',
                'null'
            ]
        },
        completion_percentage: {
            type: 'integer'
        },
        parent_id: {
            type: [
                'integer',
                'null'
            ]
        },
        created_at: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        },
        tasks: {
            type: 'array',
            description: '\'user_id\' => $this->user_id,\n\'tag_id\' => $this->tag_id,',
            items: {
                $ref: '#/components/schemas/ProjectTaskResource'
            }
        },
        tag: {
            $ref: '#/components/schemas/TagResource'
        },
        subprojects: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ProjectResource'
            }
        }
    },
    required: [
        'id',
        'title',
        'description',
        'is_completed',
        'completed_at',
        'completion_percentage',
        'parent_id',
        'created_at',
        'updated_at'
    ],
    title: 'ProjectResource'
} as const;

export const ProjectTaskRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: [
                'string',
                'null'
            ]
        },
        is_completed: {
            type: 'boolean'
        },
        completed_at: {
            type: [
                'string',
                'null'
            ],
            format: 'date-time'
        },
        project_id: {
            type: 'integer'
        }
    },
    required: [
        'title',
        'project_id'
    ],
    title: 'ProjectTaskRequest'
} as const;

export const ProjectTaskResourceSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        title: {
            type: 'string'
        },
        description: {
            type: [
                'string',
                'null'
            ]
        },
        is_completed: {
            type: 'boolean'
        },
        completed_at: {
            type: [
                'integer',
                'null'
            ]
        },
        created_at: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        },
        project_id: {
            type: 'integer'
        },
        project: {
            $ref: '#/components/schemas/ProjectResource'
        }
    },
    required: [
        'id',
        'title',
        'description',
        'is_completed',
        'completed_at',
        'created_at',
        'updated_at',
        'project_id'
    ],
    title: 'ProjectTaskResource'
} as const;

export const TagRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        tags_type: {
            type: 'string',
            enum: [
                'school',
                'reminder',
                'project',
                'task'
            ]
        }
    },
    required: [
        'name',
        'color',
        'tags_type'
    ],
    title: 'TagRequest'
} as const;

export const TagResourceSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        tags_type: {
            type: 'string'
        },
        created_at: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'color',
        'tags_type',
        'created_at',
        'updated_at'
    ],
    title: 'TagResource'
} as const;

export const TaskRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: [
                'string',
                'null'
            ]
        },
        is_completed: {
            type: 'boolean'
        },
        due_date: {
            type: [
                'string',
                'null'
            ],
            format: 'date-time'
        },
        completed_at: {
            type: [
                'string',
                'null'
            ],
            format: 'date-time'
        },
        tag_id: {
            type: [
                'integer',
                'null'
            ]
        }
    },
    required: [
        'title'
    ],
    title: 'TaskRequest'
} as const;

export const TaskResourceSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        title: {
            type: 'string'
        },
        description: {
            type: [
                'string',
                'null'
            ]
        },
        is_completed: {
            type: 'boolean'
        },
        due_date: {
            type: [
                'string',
                'null'
            ],
            format: 'date-time'
        },
        completed_at: {
            type: [
                'string',
                'null'
            ],
            format: 'date-time'
        },
        created_at: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        },
        tag: {
            description: '\'user_id\' => $this->user_id,\n\'tag_id\' => $this->tag_id,',
            $ref: '#/components/schemas/TagResource'
        }
    },
    required: [
        'id',
        'title',
        'description',
        'is_completed',
        'due_date',
        'completed_at',
        'created_at',
        'updated_at'
    ],
    title: 'TaskResource'
} as const;

export const UserResourceSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        created_at: {
            type: [
                'string',
                'null'
            ],
            format: 'date-time'
        }
    },
    required: [
        'id',
        'name',
        'email',
        'created_at'
    ],
    title: 'UserResource'
} as const;
