// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://192.168.1.25:8000/api' | (string & {});
};

/**
 * EventRequest
 */
export type EventRequest = {
    title: string;
    description: string | null;
    event_type: 'school' | 'reminder';
    due_date: string;
    tag_id?: number | null;
};

/**
 * EventResource
 */
export type EventResource = {
    id: number;
    title: string;
    description: string | null;
    event_type: string;
    due_date: string;
    created_at: string;
    updated_at: string;
    tag?: TagResource;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * ProjectRequest
 */
export type ProjectRequest = {
    title: string;
    description?: string | null;
    is_completed?: boolean;
    tag_id?: number | null;
    parent_id?: number | null;
};

/**
 * ProjectResource
 */
export type ProjectResource = {
    id: number;
    title: string;
    description: string | null;
    is_completed: boolean;
    completed_at: number | null;
    completion_percentage: number;
    parent_id: number | null;
    created_at: string;
    updated_at: string;
    /**
     * 'user_id' => $this->user_id,
     * 'tag_id' => $this->tag_id,
     */
    tasks?: Array<ProjectTaskResource>;
    tag?: TagResource;
    subprojects?: Array<ProjectResource>;
};

/**
 * ProjectTaskRequest
 */
export type ProjectTaskRequest = {
    title: string;
    description?: string | null;
    is_completed?: boolean;
    completed_at?: string | null;
    project_id: number;
};

/**
 * ProjectTaskResource
 */
export type ProjectTaskResource = {
    id: number;
    title: string;
    description: string | null;
    is_completed: boolean;
    completed_at: number | null;
    created_at: string;
    updated_at: string;
    project_id: number;
    project?: ProjectResource;
};

/**
 * TagRequest
 */
export type TagRequest = {
    name: string;
    color: string;
    tags_type: 'school' | 'reminder' | 'project' | 'task';
};

/**
 * TagResource
 */
export type TagResource = {
    id: number;
    name: string;
    color: string;
    tags_type: string;
    created_at: string;
    updated_at: string;
};

/**
 * TaskRequest
 */
export type TaskRequest = {
    title: string;
    description?: string | null;
    is_completed?: boolean;
    due_date?: string | null;
    completed_at?: string | null;
    tag_id?: number | null;
};

/**
 * TaskResource
 */
export type TaskResource = {
    id: number;
    title: string;
    description: string | null;
    is_completed: boolean;
    due_date: string | null;
    completed_at: string | null;
    created_at: string;
    updated_at: string;
    /**
     * 'user_id' => $this->user_id,
     * 'tag_id' => $this->tag_id,
     */
    tag?: TagResource;
};

/**
 * UserResource
 */
export type UserResource = {
    id: number;
    name: string;
    email: string;
    created_at: string | null;
};

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * `UserResource`
     */
    200: {
        data: UserResource;
    };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    200: {
        message: 'running';
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * No content
     */
    204: void;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type LogoutErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type DashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/dashboard';
};

export type DashboardErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type DashboardError = DashboardErrors[keyof DashboardErrors];

export type DashboardResponses = {
    200: {
        today: {
            tasks: Array<TaskResource>;
            reminders: Array<EventResource>;
            school: Array<EventResource>;
        };
        this_week: {
            tasks: Array<TaskResource>;
            reminders: Array<EventResource>;
            school: Array<EventResource>;
        };
    };
};

export type DashboardResponse = DashboardResponses[keyof DashboardResponses];

export type VerificationSendData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/email/verification-notification';
};

export type VerificationSendErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type VerificationSendError = VerificationSendErrors[keyof VerificationSendErrors];

export type VerificationSendResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type VerificationSendResponse = VerificationSendResponses[keyof VerificationSendResponses];

export type EventsIndexData = {
    body?: never;
    path?: never;
    query?: {
        event_type?: 'school' | 'reminder';
    };
    url: '/v1/events';
};

export type EventsIndexErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type EventsIndexError = EventsIndexErrors[keyof EventsIndexErrors];

export type EventsIndexResponses = {
    /**
     * Array of `EventResource`
     */
    200: {
        data: Array<EventResource>;
    } | {
        before: Array<EventResource>;
        today: Array<EventResource>;
        thisWeek: Array<EventResource>;
        nextWeek: Array<EventResource>;
        later: Array<EventResource>;
    };
};

export type EventsIndexResponse = EventsIndexResponses[keyof EventsIndexResponses];

export type EventsStoreData = {
    body: EventRequest;
    path?: never;
    query?: never;
    url: '/v1/events';
};

export type EventsStoreErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type EventsStoreError = EventsStoreErrors[keyof EventsStoreErrors];

export type EventsStoreResponses = {
    /**
     * `EventResource`
     */
    200: {
        data: EventResource;
    };
};

export type EventsStoreResponse = EventsStoreResponses[keyof EventsStoreResponses];

export type EventsDestroyData = {
    body?: never;
    path: {
        /**
         * The event ID
         */
        event: number;
    };
    query?: never;
    url: '/v1/events/{event}';
};

export type EventsDestroyErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type EventsDestroyError = EventsDestroyErrors[keyof EventsDestroyErrors];

export type EventsDestroyResponses = {
    200: Array<unknown>;
};

export type EventsDestroyResponse = EventsDestroyResponses[keyof EventsDestroyResponses];

export type EventsShowData = {
    body?: never;
    path: {
        /**
         * The event ID
         */
        event: number;
    };
    query?: never;
    url: '/v1/events/{event}';
};

export type EventsShowErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type EventsShowError = EventsShowErrors[keyof EventsShowErrors];

export type EventsShowResponses = {
    /**
     * `EventResource`
     */
    200: {
        data: EventResource;
    };
};

export type EventsShowResponse = EventsShowResponses[keyof EventsShowResponses];

export type EventsUpdateData = {
    body: EventRequest;
    path: {
        /**
         * The event ID
         */
        event: number;
    };
    query?: never;
    url: '/v1/events/{event}';
};

export type EventsUpdateErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type EventsUpdateError = EventsUpdateErrors[keyof EventsUpdateErrors];

export type EventsUpdateResponses = {
    /**
     * `EventResource`
     */
    200: {
        data: EventResource;
    };
};

export type EventsUpdateResponse = EventsUpdateResponses[keyof EventsUpdateResponses];

export type PasswordStoreData = {
    body: {
        token: string;
        email: string;
        password: string;
        password_confirmation: string;
    };
    path?: never;
    query?: never;
    url: '/reset-password';
};

export type PasswordStoreErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type PasswordStoreError = PasswordStoreErrors[keyof PasswordStoreErrors];

export type PasswordStoreResponses = {
    200: {
        status: null | Array<unknown> | string;
    };
};

export type PasswordStoreResponse = PasswordStoreResponses[keyof PasswordStoreResponses];

export type PasswordEmailData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/forgot-password';
};

export type PasswordEmailErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type PasswordEmailError = PasswordEmailErrors[keyof PasswordEmailErrors];

export type PasswordEmailResponses = {
    200: {
        status: null | Array<unknown> | string;
    };
};

export type PasswordEmailResponse = PasswordEmailResponses[keyof PasswordEmailResponses];

export type ProjectsBreadcrumbData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}/breadcrumb';
};

export type ProjectsBreadcrumbErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsBreadcrumbError = ProjectsBreadcrumbErrors[keyof ProjectsBreadcrumbErrors];

export type ProjectsBreadcrumbResponses = {
    200: Array<string>;
};

export type ProjectsBreadcrumbResponse = ProjectsBreadcrumbResponses[keyof ProjectsBreadcrumbResponses];

export type ProjectsIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type ProjectsIndexErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsIndexError = ProjectsIndexErrors[keyof ProjectsIndexErrors];

export type ProjectsIndexResponses = {
    200: {
        completed: Array<ProjectResource>;
        uncompleted: Array<ProjectResource>;
    };
};

export type ProjectsIndexResponse = ProjectsIndexResponses[keyof ProjectsIndexResponses];

export type ProjectsStoreData = {
    body: ProjectRequest;
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type ProjectsStoreErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ProjectsStoreError = ProjectsStoreErrors[keyof ProjectsStoreErrors];

export type ProjectsStoreResponses = {
    /**
     * `ProjectResource`
     */
    200: {
        data: ProjectResource;
    };
};

export type ProjectsStoreResponse = ProjectsStoreResponses[keyof ProjectsStoreResponses];

export type ProjectsDestroyData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}';
};

export type ProjectsDestroyErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsDestroyError = ProjectsDestroyErrors[keyof ProjectsDestroyErrors];

export type ProjectsDestroyResponses = {
    200: Array<unknown>;
};

export type ProjectsDestroyResponse = ProjectsDestroyResponses[keyof ProjectsDestroyResponses];

export type ProjectsShowData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}';
};

export type ProjectsShowErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsShowError = ProjectsShowErrors[keyof ProjectsShowErrors];

export type ProjectsShowResponses = {
    /**
     * `ProjectResource`
     */
    200: {
        data: ProjectResource;
    };
};

export type ProjectsShowResponse = ProjectsShowResponses[keyof ProjectsShowResponses];

export type ProjectsUpdateData = {
    body: ProjectRequest;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}';
};

export type ProjectsUpdateErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ProjectsUpdateError = ProjectsUpdateErrors[keyof ProjectsUpdateErrors];

export type ProjectsUpdateResponses = {
    /**
     * `ProjectResource`
     */
    200: {
        data: ProjectResource;
    };
};

export type ProjectsUpdateResponse = ProjectsUpdateResponses[keyof ProjectsUpdateResponses];

export type ProjectsCompleteData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}/complete';
};

export type ProjectsCompleteErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsCompleteError = ProjectsCompleteErrors[keyof ProjectsCompleteErrors];

export type ProjectsCompleteResponses = {
    200: Array<unknown>;
};

export type ProjectsCompleteResponse = ProjectsCompleteResponses[keyof ProjectsCompleteResponses];

export type ProjectsReopenData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}/reopen';
};

export type ProjectsReopenErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsReopenError = ProjectsReopenErrors[keyof ProjectsReopenErrors];

export type ProjectsReopenResponses = {
    200: Array<unknown>;
};

export type ProjectsReopenResponse = ProjectsReopenResponses[keyof ProjectsReopenResponses];

export type ProjectsTasksIndexData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}/tasks';
};

export type ProjectsTasksIndexErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsTasksIndexError = ProjectsTasksIndexErrors[keyof ProjectsTasksIndexErrors];

export type ProjectsTasksIndexResponses = {
    /**
     * Array of `ProjectTaskResource`
     */
    200: {
        data: Array<ProjectTaskResource>;
    };
};

export type ProjectsTasksIndexResponse = ProjectsTasksIndexResponses[keyof ProjectsTasksIndexResponses];

export type ProjectsTasksStoreData = {
    body: ProjectTaskRequest;
    path: {
        /**
         * The project ID
         */
        project: number;
    };
    query?: never;
    url: '/v1/projects/{project}/tasks';
};

export type ProjectsTasksStoreErrors = {
    /**
     * An error
     */
    400: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ProjectsTasksStoreError = ProjectsTasksStoreErrors[keyof ProjectsTasksStoreErrors];

export type ProjectsTasksStoreResponses = {
    /**
     * `ProjectTaskResource`
     */
    200: {
        data: ProjectTaskResource;
    };
};

export type ProjectsTasksStoreResponse = ProjectsTasksStoreResponses[keyof ProjectsTasksStoreResponses];

export type ProjectsTasksDestroyData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/projects/{project}/tasks/{task}';
};

export type ProjectsTasksDestroyErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsTasksDestroyError = ProjectsTasksDestroyErrors[keyof ProjectsTasksDestroyErrors];

export type ProjectsTasksDestroyResponses = {
    200: Array<unknown>;
};

export type ProjectsTasksDestroyResponse = ProjectsTasksDestroyResponses[keyof ProjectsTasksDestroyResponses];

export type ProjectsTasksShowData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/projects/{project}/tasks/{task}';
};

export type ProjectsTasksShowErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsTasksShowError = ProjectsTasksShowErrors[keyof ProjectsTasksShowErrors];

export type ProjectsTasksShowResponses = {
    /**
     * `ProjectTaskResource`
     */
    200: {
        data: ProjectTaskResource;
    };
};

export type ProjectsTasksShowResponse = ProjectsTasksShowResponses[keyof ProjectsTasksShowResponses];

export type ProjectsTasksUpdateData = {
    body: ProjectTaskRequest;
    path: {
        /**
         * The project ID
         */
        project: number;
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/projects/{project}/tasks/{task}';
};

export type ProjectsTasksUpdateErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ProjectsTasksUpdateError = ProjectsTasksUpdateErrors[keyof ProjectsTasksUpdateErrors];

export type ProjectsTasksUpdateResponses = {
    /**
     * `ProjectTaskResource`
     */
    200: {
        data: ProjectTaskResource;
    };
};

export type ProjectsTasksUpdateResponse = ProjectsTasksUpdateResponses[keyof ProjectsTasksUpdateResponses];

export type ProjectsTasksCompleteData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/projects/{project}/tasks/{task}/complete';
};

export type ProjectsTasksCompleteErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsTasksCompleteError = ProjectsTasksCompleteErrors[keyof ProjectsTasksCompleteErrors];

export type ProjectsTasksCompleteResponses = {
    200: Array<unknown>;
};

export type ProjectsTasksCompleteResponse = ProjectsTasksCompleteResponses[keyof ProjectsTasksCompleteResponses];

export type ProjectsTasksReopenData = {
    body?: never;
    path: {
        /**
         * The project ID
         */
        project: number;
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/projects/{project}/tasks/{task}/reopen';
};

export type ProjectsTasksReopenErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProjectsTasksReopenError = ProjectsTasksReopenErrors[keyof ProjectsTasksReopenErrors];

export type ProjectsTasksReopenResponses = {
    200: Array<unknown>;
};

export type ProjectsTasksReopenResponse = ProjectsTasksReopenResponses[keyof ProjectsTasksReopenResponses];

export type RegisterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * No content
     */
    204: void;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type TagsIndexData = {
    body?: never;
    path?: never;
    query?: {
        tags_type?: 'school' | 'reminder' | 'project' | 'task';
    };
    url: '/v1/tags';
};

export type TagsIndexErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type TagsIndexError = TagsIndexErrors[keyof TagsIndexErrors];

export type TagsIndexResponses = {
    /**
     * Array of `TagResource`
     */
    200: {
        project: Array<unknown>;
        reminder: Array<unknown>;
        school: Array<unknown>;
        task: Array<unknown>;
    } | {
        data: Array<TagResource>;
    };
};

export type TagsIndexResponse = TagsIndexResponses[keyof TagsIndexResponses];

export type TagsStoreData = {
    body: TagRequest;
    path?: never;
    query?: never;
    url: '/v1/tags';
};

export type TagsStoreErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type TagsStoreError = TagsStoreErrors[keyof TagsStoreErrors];

export type TagsStoreResponses = {
    /**
     * `TagResource`
     */
    200: {
        data: TagResource;
    };
};

export type TagsStoreResponse = TagsStoreResponses[keyof TagsStoreResponses];

export type TagsDestroyData = {
    body?: never;
    path: {
        /**
         * The tag ID
         */
        tag: number;
    };
    query?: never;
    url: '/v1/tags/{tag}';
};

export type TagsDestroyErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    422: {
        message: 'Tag nelze smazat, protože je používán.';
    };
};

export type TagsDestroyError = TagsDestroyErrors[keyof TagsDestroyErrors];

export type TagsDestroyResponses = {
    200: Array<unknown>;
};

export type TagsDestroyResponse = TagsDestroyResponses[keyof TagsDestroyResponses];

export type TagsShowData = {
    body?: never;
    path: {
        /**
         * The tag ID
         */
        tag: number;
    };
    query?: never;
    url: '/v1/tags/{tag}';
};

export type TagsShowErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TagsShowError = TagsShowErrors[keyof TagsShowErrors];

export type TagsShowResponses = {
    /**
     * `TagResource`
     */
    200: {
        data: TagResource;
    };
};

export type TagsShowResponse = TagsShowResponses[keyof TagsShowResponses];

export type TagsUpdateData = {
    body: TagRequest;
    path: {
        /**
         * The tag ID
         */
        tag: number;
    };
    query?: never;
    url: '/v1/tags/{tag}';
};

export type TagsUpdateErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type TagsUpdateError = TagsUpdateErrors[keyof TagsUpdateErrors];

export type TagsUpdateResponses = {
    /**
     * `TagResource`
     */
    200: {
        data: TagResource;
    };
};

export type TagsUpdateResponse = TagsUpdateResponses[keyof TagsUpdateResponses];

export type TasksIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/tasks';
};

export type TasksIndexErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TasksIndexError = TasksIndexErrors[keyof TasksIndexErrors];

export type TasksIndexResponses = {
    200: {
        completed: Array<unknown>;
        nonCompletedNoDate: Array<unknown>;
        nonCompletedWithDate: Array<unknown>;
    };
};

export type TasksIndexResponse = TasksIndexResponses[keyof TasksIndexResponses];

export type TasksStoreData = {
    body: TaskRequest;
    path?: never;
    query?: never;
    url: '/v1/tasks';
};

export type TasksStoreErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type TasksStoreError = TasksStoreErrors[keyof TasksStoreErrors];

export type TasksStoreResponses = {
    /**
     * `TaskResource`
     */
    200: {
        data: TaskResource;
    };
};

export type TasksStoreResponse = TasksStoreResponses[keyof TasksStoreResponses];

export type TasksDestroyData = {
    body?: never;
    path: {
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/tasks/{task}';
};

export type TasksDestroyErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TasksDestroyError = TasksDestroyErrors[keyof TasksDestroyErrors];

export type TasksDestroyResponses = {
    200: Array<unknown>;
};

export type TasksDestroyResponse = TasksDestroyResponses[keyof TasksDestroyResponses];

export type TasksShowData = {
    body?: never;
    path: {
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/tasks/{task}';
};

export type TasksShowErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TasksShowError = TasksShowErrors[keyof TasksShowErrors];

export type TasksShowResponses = {
    /**
     * `TaskResource`
     */
    200: {
        data: TaskResource;
    };
};

export type TasksShowResponse = TasksShowResponses[keyof TasksShowResponses];

export type TasksUpdateData = {
    body: TaskRequest;
    path: {
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/tasks/{task}';
};

export type TasksUpdateErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type TasksUpdateError = TasksUpdateErrors[keyof TasksUpdateErrors];

export type TasksUpdateResponses = {
    /**
     * `TaskResource`
     */
    200: {
        data: TaskResource;
    };
};

export type TasksUpdateResponse = TasksUpdateResponses[keyof TasksUpdateResponses];

export type TasksCompleteData = {
    body?: never;
    path: {
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/tasks/{task}/complete';
};

export type TasksCompleteErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TasksCompleteError = TasksCompleteErrors[keyof TasksCompleteErrors];

export type TasksCompleteResponses = {
    200: Array<unknown>;
};

export type TasksCompleteResponse = TasksCompleteResponses[keyof TasksCompleteResponses];

export type TasksReopenData = {
    body?: never;
    path: {
        /**
         * The task ID
         */
        task: number;
    };
    query?: never;
    url: '/v1/tasks/{task}/reopen';
};

export type TasksReopenErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TasksReopenError = TasksReopenErrors[keyof TasksReopenErrors];

export type TasksReopenResponses = {
    200: Array<unknown>;
};

export type TasksReopenResponse = TasksReopenResponses[keyof TasksReopenResponses];

export type VerificationVerifyData = {
    body?: never;
    path: {
        id: string;
        hash: string;
    };
    query?: never;
    url: '/verify-email/{id}/{hash}';
};

export type VerificationVerifyErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type VerificationVerifyError = VerificationVerifyErrors[keyof VerificationVerifyErrors];

export type VerificationVerifyResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type VerificationVerifyResponse = VerificationVerifyResponses[keyof VerificationVerifyResponses];
